# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-11 13:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='end',
            field=models.DateTimeField(verbose_name='End time'),
        ),
        migrations.AlterField(
            model_name='task',
            name='start',
            field=models.DateTimeField(verbose_name='Start time'),
        ),
    ]
