# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-18 10:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cal', '0003_auto_20170511_1538'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='end',
        ),
    ]
