# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-01 10:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('week', '0003_auto_20170512_1519'),
    ]

    operations = [
        migrations.AddField(
            model_name='worker',
            name='max_hours',
            field=models.IntegerField(default=12),
        ),
        migrations.AddField(
            model_name='worker',
            name='start_hour',
            field=models.IntegerField(default=8),
        ),
    ]
